# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: steammessages_offline.steamclient.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import google.protobuf.descriptor_pb2
import steammessages_unified_base.steamclient_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='steammessages_offline.steamclient.proto',
  package='',
  serialized_pb=_b('\n\'steammessages_offline.steamclient.proto\x1a google/protobuf/descriptor.proto\x1a,steammessages_unified_base.steamclient.proto\":\n&COffline_GetOfflineLogonTicket_Request\x12\x10\n\x08priority\x18\x01 \x01(\r\"W\n\'COffline_GetOfflineLogonTicket_Response\x12\x19\n\x11serialized_ticket\x18\x01 \x01(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c\"0\n.COffline_GetUnsignedOfflineLogonTicket_Request\"O\n\x1b\x43Offline_OfflineLogonTicket\x12\x11\n\taccountid\x18\x01 \x01(\r\x12\x1d\n\x15rtime32_creation_time\x18\x02 \x01(\x07\"_\n/COffline_GetUnsignedOfflineLogonTicket_Response\x12,\n\x06ticket\x18\x01 \x01(\x0b\x32\x1c.COffline_OfflineLogonTicket2\xa3\x03\n\x07Offline\x12\xb5\x01\n\x15GetOfflineLogonTicket\x12\'.COffline_GetOfflineLogonTicket_Request\x1a(.COffline_GetOfflineLogonTicket_Response\"I\x82\xb5\x18\x45Get a serialized and signed offline logon ticket for the current user\x12\xc1\x01\n\x1dGetUnsignedOfflineLogonTicket\x12/.COffline_GetUnsignedOfflineLogonTicket_Request\x1a\x30.COffline_GetUnsignedOfflineLogonTicket_Response\"=\x82\xb5\x18\x39Get an unsigned offline logon ticket for the current user\x1a\x1c\x82\xb5\x18\x18Offline settings service')
  ,
  dependencies=[google.protobuf.descriptor_pb2.DESCRIPTOR,steammessages_unified_base.steamclient_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_COFFLINE_GETOFFLINELOGONTICKET_REQUEST = _descriptor.Descriptor(
  name='COffline_GetOfflineLogonTicket_Request',
  full_name='COffline_GetOfflineLogonTicket_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='priority', full_name='COffline_GetOfflineLogonTicket_Request.priority', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=181,
)


_COFFLINE_GETOFFLINELOGONTICKET_RESPONSE = _descriptor.Descriptor(
  name='COffline_GetOfflineLogonTicket_Response',
  full_name='COffline_GetOfflineLogonTicket_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='serialized_ticket', full_name='COffline_GetOfflineLogonTicket_Response.serialized_ticket', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='COffline_GetOfflineLogonTicket_Response.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=270,
)


_COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_REQUEST = _descriptor.Descriptor(
  name='COffline_GetUnsignedOfflineLogonTicket_Request',
  full_name='COffline_GetUnsignedOfflineLogonTicket_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=320,
)


_COFFLINE_OFFLINELOGONTICKET = _descriptor.Descriptor(
  name='COffline_OfflineLogonTicket',
  full_name='COffline_OfflineLogonTicket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountid', full_name='COffline_OfflineLogonTicket.accountid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rtime32_creation_time', full_name='COffline_OfflineLogonTicket.rtime32_creation_time', index=1,
      number=2, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=401,
)


_COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_RESPONSE = _descriptor.Descriptor(
  name='COffline_GetUnsignedOfflineLogonTicket_Response',
  full_name='COffline_GetUnsignedOfflineLogonTicket_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ticket', full_name='COffline_GetUnsignedOfflineLogonTicket_Response.ticket', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=403,
  serialized_end=498,
)

_COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_RESPONSE.fields_by_name['ticket'].message_type = _COFFLINE_OFFLINELOGONTICKET
DESCRIPTOR.message_types_by_name['COffline_GetOfflineLogonTicket_Request'] = _COFFLINE_GETOFFLINELOGONTICKET_REQUEST
DESCRIPTOR.message_types_by_name['COffline_GetOfflineLogonTicket_Response'] = _COFFLINE_GETOFFLINELOGONTICKET_RESPONSE
DESCRIPTOR.message_types_by_name['COffline_GetUnsignedOfflineLogonTicket_Request'] = _COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_REQUEST
DESCRIPTOR.message_types_by_name['COffline_OfflineLogonTicket'] = _COFFLINE_OFFLINELOGONTICKET
DESCRIPTOR.message_types_by_name['COffline_GetUnsignedOfflineLogonTicket_Response'] = _COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_RESPONSE

COffline_GetOfflineLogonTicket_Request = _reflection.GeneratedProtocolMessageType('COffline_GetOfflineLogonTicket_Request', (_message.Message,), dict(
  DESCRIPTOR = _COFFLINE_GETOFFLINELOGONTICKET_REQUEST,
  __module__ = 'steammessages_offline.steamclient_pb2'
  # @@protoc_insertion_point(class_scope:COffline_GetOfflineLogonTicket_Request)
  ))
_sym_db.RegisterMessage(COffline_GetOfflineLogonTicket_Request)

COffline_GetOfflineLogonTicket_Response = _reflection.GeneratedProtocolMessageType('COffline_GetOfflineLogonTicket_Response', (_message.Message,), dict(
  DESCRIPTOR = _COFFLINE_GETOFFLINELOGONTICKET_RESPONSE,
  __module__ = 'steammessages_offline.steamclient_pb2'
  # @@protoc_insertion_point(class_scope:COffline_GetOfflineLogonTicket_Response)
  ))
_sym_db.RegisterMessage(COffline_GetOfflineLogonTicket_Response)

COffline_GetUnsignedOfflineLogonTicket_Request = _reflection.GeneratedProtocolMessageType('COffline_GetUnsignedOfflineLogonTicket_Request', (_message.Message,), dict(
  DESCRIPTOR = _COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_REQUEST,
  __module__ = 'steammessages_offline.steamclient_pb2'
  # @@protoc_insertion_point(class_scope:COffline_GetUnsignedOfflineLogonTicket_Request)
  ))
_sym_db.RegisterMessage(COffline_GetUnsignedOfflineLogonTicket_Request)

COffline_OfflineLogonTicket = _reflection.GeneratedProtocolMessageType('COffline_OfflineLogonTicket', (_message.Message,), dict(
  DESCRIPTOR = _COFFLINE_OFFLINELOGONTICKET,
  __module__ = 'steammessages_offline.steamclient_pb2'
  # @@protoc_insertion_point(class_scope:COffline_OfflineLogonTicket)
  ))
_sym_db.RegisterMessage(COffline_OfflineLogonTicket)

COffline_GetUnsignedOfflineLogonTicket_Response = _reflection.GeneratedProtocolMessageType('COffline_GetUnsignedOfflineLogonTicket_Response', (_message.Message,), dict(
  DESCRIPTOR = _COFFLINE_GETUNSIGNEDOFFLINELOGONTICKET_RESPONSE,
  __module__ = 'steammessages_offline.steamclient_pb2'
  # @@protoc_insertion_point(class_scope:COffline_GetUnsignedOfflineLogonTicket_Response)
  ))
_sym_db.RegisterMessage(COffline_GetUnsignedOfflineLogonTicket_Response)


# @@protoc_insertion_point(module_scope)
