# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='iclient_objects.proto',
  package='',
  serialized_pb='\n\x15iclient_objects.proto\"\xa8\x02\n\rClientAppInfo\x12\r\n\x05\x61ppid\x18\x01 \x01(\r\x12\x10\n\x08\x66\x61vorite\x18\x02 \x01(\x08\x12\x11\n\tinstalled\x18\x03 \x01(\x08\x12\x13\n\x0b\x61uto_update\x18\x04 \x01(\x08\x12\x10\n\x08\x63\x61tegory\x18\x05 \x01(\t\x12\x10\n\x08\x61pp_type\x18\x06 \x01(\t\x12\x13\n\x0b\x64ownloading\x18\x07 \x01(\x08\x12\x17\n\x0f\x64ownload_paused\x18\x08 \x01(\x08\x12\x1b\n\x13\x62ytes_download_rate\x18\t \x01(\r\x12\x18\n\x10\x62ytes_downloaded\x18\n \x01(\x04\x12\x14\n\x0c\x62ytes_needed\x18\x0b \x01(\x04\x12\x10\n\x08\x63hanging\x18\x0c \x01(\x08\x12\x1d\n\x15\x61vailable_on_platform\x18\r \x01(\x08')




_CLIENTAPPINFO = descriptor.Descriptor(
  name='ClientAppInfo',
  full_name='ClientAppInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='appid', full_name='ClientAppInfo.appid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='favorite', full_name='ClientAppInfo.favorite', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='installed', full_name='ClientAppInfo.installed', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='auto_update', full_name='ClientAppInfo.auto_update', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='category', full_name='ClientAppInfo.category', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='app_type', full_name='ClientAppInfo.app_type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='downloading', full_name='ClientAppInfo.downloading', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='download_paused', full_name='ClientAppInfo.download_paused', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bytes_download_rate', full_name='ClientAppInfo.bytes_download_rate', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bytes_downloaded', full_name='ClientAppInfo.bytes_downloaded', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='bytes_needed', full_name='ClientAppInfo.bytes_needed', index=10,
      number=11, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='changing', full_name='ClientAppInfo.changing', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='available_on_platform', full_name='ClientAppInfo.available_on_platform', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=26,
  serialized_end=322,
)

DESCRIPTOR.message_types_by_name['ClientAppInfo'] = _CLIENTAPPINFO

class ClientAppInfo(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CLIENTAPPINFO
  
  # @@protoc_insertion_point(class_scope:ClientAppInfo)

# @@protoc_insertion_point(module_scope)
