# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: steammessages_unified_test.steamclient.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import google.protobuf.descriptor_pb2
import steammessages_unified_base.steamclient_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='steammessages_unified_test.steamclient.proto',
  package='',
  serialized_pb=_b('\n,steammessages_unified_test.steamclient.proto\x1a google/protobuf/descriptor.proto\x1a,steammessages_unified_base.steamclient.proto\"G\n CMsgTest_MessageToClient_Request\x12#\n\tsome_text\x18\x01 \x01(\tB\x10\x82\xb5\x18\x0cSome string.\"H\n!CMsgTest_MessageToClient_Response\x12#\n\tsome_text\x18\x01 \x01(\tB\x10\x82\xb5\x18\x0cSome string.\"I\n\"CMsgTest_NotifyClient_Notification\x12#\n\tsome_text\x18\x01 \x01(\tB\x10\x82\xb5\x18\x0cSome string.\"G\n CMsgTest_MessageToServer_Request\x12#\n\tsome_text\x18\x01 \x01(\tB\x10\x82\xb5\x18\x0cSome string.\"H\n!CMsgTest_MessageToServer_Response\x12#\n\tsome_text\x18\x01 \x01(\tB\x10\x82\xb5\x18\x0cSome string.\"I\n\"CMsgTest_NotifyServer_Notification\x12#\n\tsome_text\x18\x01 \x01(\tB\x10\x82\xb5\x18\x0cSome string.2\x83\x02\n\x0fTestSteamClient\x12\x81\x01\n\x0fMessageToClient\x12!.CMsgTest_MessageToClient_Request\x1a\".CMsgTest_MessageToClient_Response\"\'\x82\xb5\x18#Some description - MessageToClient.\x12\x66\n\x0cNotifyClient\x12#.CMsgTest_NotifyClient_Notification\x1a\x0b.NoResponse\"$\x82\xb5\x18 Some description - NotifyClient.\x1a\x04\xc0\xb5\x18\x02\x32\x82\x02\n\x14TestServerFromClient\x12\x81\x01\n\x0fMessageToServer\x12!.CMsgTest_MessageToServer_Request\x1a\".CMsgTest_MessageToServer_Response\"\'\x82\xb5\x18#Some description - MessageToServer.\x12\x66\n\x0cNotifyServer\x12#.CMsgTest_NotifyServer_Notification\x1a\x0b.NoResponse\"$\x82\xb5\x18 Some description - NotifyServer.')
  ,
  dependencies=[google.protobuf.descriptor_pb2.DESCRIPTOR,steammessages_unified_base.steamclient_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CMSGTEST_MESSAGETOCLIENT_REQUEST = _descriptor.Descriptor(
  name='CMsgTest_MessageToClient_Request',
  full_name='CMsgTest_MessageToClient_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='some_text', full_name='CMsgTest_MessageToClient_Request.some_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\265\030\014Some string.'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=199,
)


_CMSGTEST_MESSAGETOCLIENT_RESPONSE = _descriptor.Descriptor(
  name='CMsgTest_MessageToClient_Response',
  full_name='CMsgTest_MessageToClient_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='some_text', full_name='CMsgTest_MessageToClient_Response.some_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\265\030\014Some string.'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=273,
)


_CMSGTEST_NOTIFYCLIENT_NOTIFICATION = _descriptor.Descriptor(
  name='CMsgTest_NotifyClient_Notification',
  full_name='CMsgTest_NotifyClient_Notification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='some_text', full_name='CMsgTest_NotifyClient_Notification.some_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\265\030\014Some string.'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=348,
)


_CMSGTEST_MESSAGETOSERVER_REQUEST = _descriptor.Descriptor(
  name='CMsgTest_MessageToServer_Request',
  full_name='CMsgTest_MessageToServer_Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='some_text', full_name='CMsgTest_MessageToServer_Request.some_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\265\030\014Some string.'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=421,
)


_CMSGTEST_MESSAGETOSERVER_RESPONSE = _descriptor.Descriptor(
  name='CMsgTest_MessageToServer_Response',
  full_name='CMsgTest_MessageToServer_Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='some_text', full_name='CMsgTest_MessageToServer_Response.some_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\265\030\014Some string.'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=495,
)


_CMSGTEST_NOTIFYSERVER_NOTIFICATION = _descriptor.Descriptor(
  name='CMsgTest_NotifyServer_Notification',
  full_name='CMsgTest_NotifyServer_Notification',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='some_text', full_name='CMsgTest_NotifyServer_Notification.some_text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\265\030\014Some string.'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=497,
  serialized_end=570,
)

DESCRIPTOR.message_types_by_name['CMsgTest_MessageToClient_Request'] = _CMSGTEST_MESSAGETOCLIENT_REQUEST
DESCRIPTOR.message_types_by_name['CMsgTest_MessageToClient_Response'] = _CMSGTEST_MESSAGETOCLIENT_RESPONSE
DESCRIPTOR.message_types_by_name['CMsgTest_NotifyClient_Notification'] = _CMSGTEST_NOTIFYCLIENT_NOTIFICATION
DESCRIPTOR.message_types_by_name['CMsgTest_MessageToServer_Request'] = _CMSGTEST_MESSAGETOSERVER_REQUEST
DESCRIPTOR.message_types_by_name['CMsgTest_MessageToServer_Response'] = _CMSGTEST_MESSAGETOSERVER_RESPONSE
DESCRIPTOR.message_types_by_name['CMsgTest_NotifyServer_Notification'] = _CMSGTEST_NOTIFYSERVER_NOTIFICATION

CMsgTest_MessageToClient_Request = _reflection.GeneratedProtocolMessageType('CMsgTest_MessageToClient_Request', (_message.Message,), dict(
  DESCRIPTOR = _CMSGTEST_MESSAGETOCLIENT_REQUEST,
  __module__ = 'steammessages_unified_test.steamclient_pb2'
  # @@protoc_insertion_point(class_scope:CMsgTest_MessageToClient_Request)
  ))
_sym_db.RegisterMessage(CMsgTest_MessageToClient_Request)

CMsgTest_MessageToClient_Response = _reflection.GeneratedProtocolMessageType('CMsgTest_MessageToClient_Response', (_message.Message,), dict(
  DESCRIPTOR = _CMSGTEST_MESSAGETOCLIENT_RESPONSE,
  __module__ = 'steammessages_unified_test.steamclient_pb2'
  # @@protoc_insertion_point(class_scope:CMsgTest_MessageToClient_Response)
  ))
_sym_db.RegisterMessage(CMsgTest_MessageToClient_Response)

CMsgTest_NotifyClient_Notification = _reflection.GeneratedProtocolMessageType('CMsgTest_NotifyClient_Notification', (_message.Message,), dict(
  DESCRIPTOR = _CMSGTEST_NOTIFYCLIENT_NOTIFICATION,
  __module__ = 'steammessages_unified_test.steamclient_pb2'
  # @@protoc_insertion_point(class_scope:CMsgTest_NotifyClient_Notification)
  ))
_sym_db.RegisterMessage(CMsgTest_NotifyClient_Notification)

CMsgTest_MessageToServer_Request = _reflection.GeneratedProtocolMessageType('CMsgTest_MessageToServer_Request', (_message.Message,), dict(
  DESCRIPTOR = _CMSGTEST_MESSAGETOSERVER_REQUEST,
  __module__ = 'steammessages_unified_test.steamclient_pb2'
  # @@protoc_insertion_point(class_scope:CMsgTest_MessageToServer_Request)
  ))
_sym_db.RegisterMessage(CMsgTest_MessageToServer_Request)

CMsgTest_MessageToServer_Response = _reflection.GeneratedProtocolMessageType('CMsgTest_MessageToServer_Response', (_message.Message,), dict(
  DESCRIPTOR = _CMSGTEST_MESSAGETOSERVER_RESPONSE,
  __module__ = 'steammessages_unified_test.steamclient_pb2'
  # @@protoc_insertion_point(class_scope:CMsgTest_MessageToServer_Response)
  ))
_sym_db.RegisterMessage(CMsgTest_MessageToServer_Response)

CMsgTest_NotifyServer_Notification = _reflection.GeneratedProtocolMessageType('CMsgTest_NotifyServer_Notification', (_message.Message,), dict(
  DESCRIPTOR = _CMSGTEST_NOTIFYSERVER_NOTIFICATION,
  __module__ = 'steammessages_unified_test.steamclient_pb2'
  # @@protoc_insertion_point(class_scope:CMsgTest_NotifyServer_Notification)
  ))
_sym_db.RegisterMessage(CMsgTest_NotifyServer_Notification)


_CMSGTEST_MESSAGETOCLIENT_REQUEST.fields_by_name['some_text'].has_options = True
_CMSGTEST_MESSAGETOCLIENT_REQUEST.fields_by_name['some_text']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\265\030\014Some string.'))
_CMSGTEST_MESSAGETOCLIENT_RESPONSE.fields_by_name['some_text'].has_options = True
_CMSGTEST_MESSAGETOCLIENT_RESPONSE.fields_by_name['some_text']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\265\030\014Some string.'))
_CMSGTEST_NOTIFYCLIENT_NOTIFICATION.fields_by_name['some_text'].has_options = True
_CMSGTEST_NOTIFYCLIENT_NOTIFICATION.fields_by_name['some_text']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\265\030\014Some string.'))
_CMSGTEST_MESSAGETOSERVER_REQUEST.fields_by_name['some_text'].has_options = True
_CMSGTEST_MESSAGETOSERVER_REQUEST.fields_by_name['some_text']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\265\030\014Some string.'))
_CMSGTEST_MESSAGETOSERVER_RESPONSE.fields_by_name['some_text'].has_options = True
_CMSGTEST_MESSAGETOSERVER_RESPONSE.fields_by_name['some_text']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\265\030\014Some string.'))
_CMSGTEST_NOTIFYSERVER_NOTIFICATION.fields_by_name['some_text'].has_options = True
_CMSGTEST_NOTIFYSERVER_NOTIFICATION.fields_by_name['some_text']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\265\030\014Some string.'))
# @@protoc_insertion_point(module_scope)
